### ISSUE TITLE
How to solve those problems?

### ISSUE THREAD

**Issue by BetterYong** [francisyyan/rlcc#1]
Hello,Hello, I ran into some problems while running this project. I will follow the steps below:
git clone https://github.com/StanfordSNR/pantheon.git
git submodule update --init --recursive  # or tools/fetch_submodules.sh
src/experiments/setup.py --install-deps  --all
src/experiments/setup.py --setup  --all
 src/experiments/test.py local  --schmes "indigo"
Then I download the file under ‘indigo’ folder and copy it to ‘indigo’, but I have the following problems and how to solve it？
File "src/experiments/test.py", line 808, in main
    run_tests(args)
  File "src/experiments/test.py", line 749, in run_tests
    getattr(args, 'remote_path', None))
  File "/home/zouyong/pantheon/src/experiments/helpers/utils.py", line 180, in get_git_summary
    local_git_summary = check_output(git_summary_src, cwd=context.base_dir)
  File "/home/zouyong/pantheon/src/experiments/helpers/subprocess_wrappers.py", line 29, in check_output
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Thank you for your answer

**Comment by francisyyan** [comment]
What do you mean by  
> Then I download the file under ‘indigo’ folder and copy it to ‘indigo’

? Indigo, as a submodule of Pantheon, will be automatically downloaded to `pantheon/third_party/indigo` when you run `git submodule update --init`.

Regardless, the issue seems that `git_summary.sh` can't be found. Please `cd` into `pantheon/src/experiments` and check if `git_summary.sh` exists; if so, please run `git_summary.sh` first, and run `./test.py local --schemes "indigo"` if that works.

Please feel free to let us know your questions about Pantheon by posting them to our Google group: https://groups.google.com/forum/#!forum/pantheon-stanford. Thank you!
